### ISSUE TITLE
Support Compose Desktop 1.7

### ISSUE THREAD

**Issue by Cdm2883** [MayakaApps/ComposeWindowStyler#38]
**Describe the bug**
Cannot set the window style, and it throws:

```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchFieldException: delegate
	at java.base/java.lang.Class.getDeclaredField(Class.java:2782)
	at com.mayakapps.compose.windowstyler.TransparencyUtilsKt$delegateField$2.invoke(TransparencyUtils.kt:57)
	at com.mayakapps.compose.windowstyler.TransparencyUtilsKt$delegateField$2.invoke(TransparencyUtils.kt:56)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:83)
	at com.mayakapps.compose.windowstyler.TransparencyUtilsKt.getDelegateField(TransparencyUtils.kt:56)
	at com.mayakapps.compose.windowstyler.TransparencyUtilsKt.getSkiaLayer(TransparencyUtils.kt:36)
	at com.mayakapps.compose.windowstyler.TransparencyUtilsKt.isTransparent(TransparencyUtils.kt:43)
	at com.mayakapps.compose.windowstyler.windows.WindowsWindowStyleManager._init_$lambda-0(WindowsWindowStyleManager.kt:66)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

I checked the `ComposeWindow::class` and there is no `delegate` field actually.

**To Reproduce**
Just using `WindowStyle(...)`

**OS:**
 - Compose: 1.7.1
 - OS: Windows 11 24H2
 - Build: 26120.2705

**Comment by Cdm2883** [comment]
Okay... It seems be fixed in SNAPSHOT version
